"""
Django settings for inventario project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from supabase import create_client, Client
from django.conf import settings
from dotenv import load_dotenv

SUPABASE_URL = 'https://yedojhnqvbcgkmkwibcr.supabase.co'
SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllZG9qaG5xdmJjZ2tta3dpYmNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjkxMDM1MDIsImV4cCI6MjA0NDY3OTUwMn0.1x21y929lanLTlfDE37qkni7mRNZfer7MagxndlNryY'

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)


AUTH_USER_MODEL = 'inventarioapi.CustomUser'




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q)alx7))di62v2y-ij)z+a9%14^ckmx@+8d)6@95$mdjt_hjkp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

ALLOWED_HOSTS = []

DEFAULT_FILE_STORAGE = 'https://yedojhnqvbcgkmkwibcr.supabase.co/storage/v1/s3'
AWS_ACCESS_KEY_ID = os.getenv('fa194487d99b0287e9e1620dc47cc91c')
AWS_SECRET_ACCESS_KEY = os.getenv('813793dbf4b531f981e7c6b35528bcf503794d994bf6b35eaf7bab21441d1e3f')
AWS_STORAGE_BUCKET_NAME = os.getenv('ImagenProductos')
AWS_S3_ENDPOINT_URL = os.getenv('https://yedojhnqvbcgkmkwibcr.supabase.co/storage/v1/s3')
AWS_S3_REGION_NAME = os.getenv('SUPABASE_REGION_NAME', 'sa-east-1')
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_DEFAULT_ACL = None

# Application definition

APPEND_SLASH = True

INSTALLED_APPS = [
   'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventarioapi',
    'rest_framework',
    'corsheaders',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_CREDENTIALS = True
ROOT_URLCONF = 'inventario.urls'
# settings.py

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventario.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.yedojhnqvbcgkmkwibcr',
        'PASSWORD': 'Mocaypericles1234*',
        'HOST': 'aws-0-sa-east-1.pooler.supabase.com',
        'PORT': '6543',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TRANSBANK_COMMERCE_CODE = '597055555532'  # Código de comercio de prueba
TRANSBANK_API_KEY = '579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C'  # Clave API de prueba
TRANSBANK_INTEGRATION_TYPE = 'TEST' 
TRANSBANK_RETURN_URL = 'http://localhost:3000/transbank-result'  # Cambia esto a tu URL de producción cuando estés listo

# ChileExpress API Keys
CHILEXPRESS_COVERAGE_API_KEY = 'dea94f8a1852436191dbd0607052649s'
CHILEXPRESS_QUOTE_API_KEY = 'a5f3e99760d546c9b10a9f5d343192e1'