# Generated by Django 5.1.2 on 2024-12-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapi', '0004_pedido_ordenenvio_itempedido_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenenvio',
            name='numero_orden_envio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id_transaccion',
            field=models.CharField(max_length=100),
        ),
    ]
