# Generated by Django 5.1.2 on 2024-12-10 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapi', '0005_alter_ordenenvio_numero_orden_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenenvio',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordenenvio',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioapi.pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='ordenenvio',
            table='inventarioapi_ordenenvio',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='inventarioapi_pedido',
        ),
    ]
