# Generated by Django 5.1.2 on 2024-12-10 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapi', '0006_ordenenvio_costo_envio_alter_ordenenvio_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioapi.pedido'),
        ),
        migrations.AlterModelTable(
            name='itempedido',
            table='inventarioapi_itempedido',
        ),
    ]
