# Generated by Django 5.1.2 on 2024-12-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapi', '0008_envio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='envio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
