# Generated by Django 5.1.2 on 2024-12-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapi', '0010_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='subtotal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordenenvio',
            name='costo_envio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.IntegerField(),
        ),
    ]
