# Generated by Django 5.1.2 on 2024-12-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapi', '0011_alter_itempedido_precio_alter_itempedido_subtotal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
