# Generated by Django 5.1.2 on 2024-12-12 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapi', '0012_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_at',
            new_name='fecha',
        ),
    ]
